### PR TITLE
Nits

### PR DESCRIPTION
**Pull request by brettz9**

### CODE REVIEW

**Comment by brettz9** [comment]
Btw, what do you think of adding a warning regarding your subclassing of arrays raising some challenges for pipelines using ESM and Babel, and mentioning how https://www.npmjs.com/package/babel-plugin-transform-builtin-extend with:
```json
    "plugins": [
        ["babel-plugin-transform-builtin-extend", {
            "globals": ["Array"]
        }]
    ]
```

...could handle this (albeit with issues for IE <= 10).

**Comment by WebReflection** [comment]
> what do you think of adding a warning regarding your subclassing of arrays

I am using babel 7, that issue should've been solved already.

I don't care much about TypeScript, developers thinking it works well with classes will be eventually aware they chose the wrong language.

**Comment by WebReflection** [comment]
> they chose the wrong language

if they use TypeScript to transpile their code and the ESM module and they target ES5 instead of ES2015

**Comment by WebReflection** [comment]
P.S. thanks a lot for the PR. To me, beside maintenance, this module can be considered done. I suggest you to check out [hyperHTML](https://github.com/WebReflection/hyperHTML) where basically you can forget about `$` since everything is declared right away.

This module can still be handy though, which is why I've updated it for a fresh new look and some extra functionality (the `ready` one and the `new QuerySelector(...prevItems)`)

**Comment by brettz9** [comment]
My pleasure--and thanks for the responsiveness on considering, integrating, and replying to my comments! I'd like to take a closer look at your recent additions, esp. in the context of use... (And I promise not to badger you with more feature requests unless they really seem quite critical!)

By `new QuerySelector(...prevItems))` do you mean this?
```
case 'object': return new QueryResult(
...(('nodeType' in CSS || 'postMessage' in CSS) ? [CSS] : CSS)
```
Yeah, that looks very nice for wrapping existing DOM or arrays of nodes...

Re: `hyperHTML`, though I know it may be anathema to you given your admirable focus on performance (which I believe only strings will get), with my intense dislike of non-DRY aspects of HTML (within ES6 templates or whatever with its closing tags), its lesser readiness for syntax highlighting, and the issues of indenting it can cause ("prettier" notwithstanding) and the limitations for inline event attachment (in JSON/JS, the inline function can easily be added as a listener), I favor my HTML-as-JSON/JS approach as I use in my project [jamilih](https://github.com/brettz9/jamilih/)... I've been using it more and more, and feeling terrible any time I have to change from it to use string concatenation but I'm still looking to fill the gaps on the other components of jQuery which your project meets nicely (By the way "jQuery-like" is a tag available on Github repo topics you might use here.)

**Comment by WebReflection** [comment]
BTW ... I've just realized that all IEs fail because I think of the subclassed Array ... which is a bummer.

**Comment by WebReflection** [comment]
> Yeah, that looks very nice for wrapping existing DOM or arrays of nodes...

or children or NodeList or other QueryResult themselves as copied ... etc ... 😉

**Comment by WebReflection** [comment]
> Re: hyperHTML, though I know  ....

It looks like you don't have a good understanding of hyperHTML and what it does.

Strings are only the surface, events are not inline, are all actually added via addEventListener, and everything you see is a facade to native DOM operation, not a single innerHTML is basically used in the way you'd expect.

hyperHTML is like React, but it's based on standards ... no JSON approach, no strings, no inline anything, really, what you declare is what you'd create manually through the DOM interface.

Give it another try whenever you have time.

P.S. this module now is super ugly but ti works down to IE8

**Comment by brettz9** [comment]
First, a little background on me might help... I have Chronic Fatigue Syndrome, made worse by cancer treatments (now gone). Besides terrible fatigue, his has left me with a brain fog which makes it often like I am groping through the dark. Certain things require enormous concentration, despite whatever native intelligence I may have. So, my plumbing of the core of JavaScript is not accompanied as with most people with a deep understanding of a range of its practical uses. I haven't even tried React, Angular, etc., and have not truly absorbed the lessons of the likes of Backbone or such. I am interested, however, in building my core knowledge, gaining compatibility and avoiding lock-in or large projects which require a lot of deciphering to hack at oneself. My limited energy lends me therefore toward working on straightforward projects, preferably small ones which may help me learn on the job (even if my experience doesn't make me a complete noob).

So, you may see some moments of lucidity from me, and with study and experimenting, I can hack away at a problem that motivates me, but I am not able to stay on top of all of the general trends, despite my very strong desire to have the health to do so.

(Just sharing so I may minimize any frustration of my sometimes seeming obtuse...)

In exploring a little more, I see more of the advantages of hyperHTML. But I'm still left with my syntax concern. I'd like to be able to write code such as the following instead, while getting the same benefits:

```js
hyperHTML.bind(form)(jml('input', {
    class: {$: ['one', 'more', 'class'].join(' ')},
    disabled: {$: !isAuthorized},
    oninput: {$: e => document.title = e.target.value},
    value: {$: defaultInputValue}
    placeholder: {$: 'type something'}
}));
```

This would give me avoidance of closing tags, getting JavaScript syntax highlighting, indentation, bracket matching, etc., out of the box, avoidance of the unpleasantness of string indenting and nested templates, etc.

However, it seems that even if the above (modified) version of `jml` builds a template dynamically with say `eval`, there is no way, short of compilation, for my approach to get the real benefits of templates. Am I right? Is there no way to be able to use such a syntax and get the benefits of templates?

The closest I can think of is writing a template parser to parse my own JSON/JS syntax *within* template literals, but this would still suffer from syntax highlighting, IDEs not perhaps being aware of say formatting or jumping to a matching bracket, so that seems less than ideal as well...

If my templates are bulky with closing tags and the ugliness of angled brackets, the visual unpleasantness is very disruptive to me making code maintainable for myself. I can develop so much more efficiently with the code being "clean" like this to me...

**Comment by WebReflection** [comment]
```js
const {bind} = hyperHTML;

// this is a div with a class and an attribute
function render() {
  bind(document.body)`
    <div
      class=${anyClass}
      data-value=${someValue}
      onclick=${e => alert(this.dataset.value)}
    />`;
}
```

Calling `render()` is the equivalent of doing the following operations:

  * `const div = weakMap.get(document.body); || createOnce();`
  * `function createOnce() { ... }` following the description of what happens
  * `const div = document.createElement('div')`, it's done through HTMLTemplateElement but that's the same anyway
  * `div.className = anyClass`
  * `div.dataset.value = someValue`
  * `div.addEventListener('click', e => alert(this.dataset.value));`
  * `weakMap.set(document.body, div);`

The next time `render()` is called, the `div` would still be there, hence reused, and all _moving parts_ will be updated **only** if different from their previous value.

If the click listener is an arrow function, like in this case, its previous value, different from the current one, will be removed and the new arrow function will be added as listener.

If that listener is passed dynamically then it could be always the same, always different, or even null, if no listener is meant anymore.

**About syntax highlight** I use VS Code (or even just Code, the full open source one) and this plugin which highlights HTML as if it was written inside a regular HTML file.
https://github.com/WebReflection/vscode-literally-html

**Pull request merged**
